# Generated by Django 5.1 on 2024-08-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lancamentofinanceiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='data',
            field=models.DateField(),
        ),
    ]
